const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let browser;
before(async()=>{browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:'msedge'});});
after(async()=>browser?.close());
async function setup(t){const c=await browser.newContext();const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173/');await p.waitForTimeout(650);await p.evaluate(()=>{closeModal();state.audio={volume:.8,muted:false};synth=null;BADGES_DEF.forEach(b=>state.badges[b.id]=1);});t.after(async()=>{await c.close();assert.deepEqual(errors,[]);});return p;}
test('listen to question plays recorded sound without browser speech synthesis',async t=>{const p=await setup(t);await p.evaluate(()=>startLogicPattern('color'));await p.getByRole('button',{name:'🔊 听题目',exact:true}).click();await p.waitForFunction(()=>_audioEl&&!_audioEl.paused&&_audioEl.currentTime>.05,{},{timeout:3000});assert.ok(await p.evaluate(()=>_audioEl.duration>1));});
test('math prompts, hints, English sentences and story prompts all play without TTS',async t=>{const p=await setup(t);for(const code of ['startChallenge("combine");speakChallenge()','hintChallenge()','startLogicSort("length");speakLogicSort()','startEnglishLesson(0);_lesson.index=7;_lesson.step=2;renderLesson();lessonAudio()','showStoryQuiz(4);speakReading()','for(let i=0;i<4;i++){answerReading(_reading.question.answer);advanceReading();}speakStoryEvent(0)']){await p.evaluate(code=>eval(code),code);await p.waitForFunction(()=>_audioEl&&!_audioEl.paused&&_audioEl.currentTime>.02,{},{timeout:3000});assert.ok(await p.evaluate(()=>_audioEl.duration>0),code);}});
test('media start callback is not reported before audio playback actually starts',async t=>{const p=await setup(t);await p.route('**/missing-voice.mp3',r=>r.abort());await p.evaluate(()=>{window.started=0;window.failed=0;playAudio('missing-voice.mp3','missing','en',{onstart:()=>started++,onerror:()=>failed++});});await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>started),0);assert.equal(await p.evaluate(()=>failed),1);});
test('all poem cards and poem questions have valid content',async t=>{const p=await setup(t);const invalid=await p.evaluate(()=>POEMS.filter(p=>!p.a||!p.d||!Array.isArray(p.l)||!Array.isArray(p.py)||p.l.length!==p.py.length).map(p=>p.id));assert.deepEqual(invalid,[]);await p.evaluate(()=>{POEMS.forEach(p=>{showPoem(p.id);closeModal();});for(let n=1;n<=10;n++)for(let i=0;i<50;i++)generateLevelQuestions(n);});});
test('all bundled audio files decode and contain non-silent speech',{timeout:120000},async t=>{const p=await setup(t);const fs=require('node:fs');const files=fs.readdirSync(path.join(__dirname,'audio'),{recursive:true}).filter(f=>/\.(mp3|wav)$/.test(f)).map(f=>'audio/'+f.replaceAll('\\','/'));const failures=await p.evaluate(async files=>{const ac=new AudioContext(),failed=[];let next=0;async function worker(){while(next<files.length){const file=files[next++];try{const response=await fetch(file);if(!response.ok)throw Error('HTTP '+response.status);const decoded=await ac.decodeAudioData(await response.arrayBuffer());const samples=decoded.getChannelData(0);let energy=0,n=0;for(let i=0;i<samples.length;i+=23){energy+=samples[i]*samples[i];n++;}if(decoded.duration<.08||Math.sqrt(energy/n)<.0003)throw Error('Empty or silent clip');}catch(e){failed.push(file+': '+e.message);}}}await Promise.all([worker(),worker(),worker(),worker()]);await ac.close();return failed;},files);console.log('Decoded audio files: '+files.length);assert.deepEqual(failures,[]);});
test('every generated math prompt and logic hint resolves to a bundled clip',async t=>{const p=await setup(t);const missing=await p.evaluate(()=>{const missing=new Set();for(const kind of ['combine','make','compare','pattern'])for(const level of [0,1])for(let i=0;i<300;i++){const q=makeChallengeQuestion(kind,level,i);for(const text of [q.prompt,q.hint,q.explain])if(!recordedSpeechClips(text,'child'))missing.add(text);}for(const level of [0,1,2])for(const dim of ['color','shape','size'])for(let i=0;i<50;i++){state.logic.level=level;startLogicPattern(dim);const text='圈起来的是重复的一组：'+_logicPattern.cycle.map(v=>patternLabel(dim,v)).join('、')+'。再照着排一遍。';if(!recordedSpeechClips(text,'child'))missing.add(text);}return [...missing];});assert.deepEqual(missing,[]);});
test('recorded audio responds to volume, mute, repeated clicks and closing',async t=>{const p=await setup(t);await p.evaluate(()=>{startLogicSort('length');for(let i=0;i<6;i++)speakLogicSort();});await p.waitForFunction(()=>audioPlayback.status==='playing');await p.evaluate(()=>setVolume(30));assert.equal(await p.evaluate(()=>_audioEl.volume),.3);await p.evaluate(()=>toggleMute());assert.equal(await p.evaluate(()=>_audioEl.paused),true);await p.evaluate(()=>{toggleMute();speakLogicSort();closeModal();});await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>_audioEl.paused),true);assert.equal(await p.evaluate(()=>audioPlayback.status),'idle');});
test('every story page and poem recording is keyed to its exact current text',async t=>{const p=await setup(t);const crypto=require('node:crypto');const manifest=require('./audio/prompts/manifest.json');const result=await p.evaluate(()=>[...STORIES.flatMap(s=>s.p.map(text=>({text,clips:recordedSpeechClips(text,'story')}))),...POEMS.map(p=>{const text=p.t+'，'+p.d+'，'+p.a+'。'+p.l.join('，');return {text,clips:recordedSpeechClips(text,'recite')};})]);assert.equal(result.length,220);for(const entry of result){const hash=crypto.createHash('sha256').update('zh|'+entry.text.trim().replace(/\s+/g,' ')).digest('hex').slice(0,20);assert.deepEqual(entry.clips,['audio/prompts/'+hash+'.mp3']);assert.ok(manifest.some(m=>m.text===entry.text&&m.file==='audio/prompts/'+hash+'.wav'));}});
test('poem line and picture prompts and letter friends have offline recordings',async t=>{const p=await setup(t);const missing=await p.evaluate(()=>{const missing=[];for(const poem of POEMS)for(const line of poem.l)for(const text of [line,line.slice(-1)])if(!recordedSpeechClips(text,'child'))missing.push(text);for(const rows of Object.values(POEM_PICTURES))for(const row of rows)for(const i of [0,2,4,6])if(!recordedSpeechClips(row[i],'child'))missing.push(row[i]);for(const w of LETTER_FRIENDS)if(!recordedSpeechClips(w.w,'en'))missing.push(w.w);return missing;});assert.deepEqual(missing,[]);await p.evaluate(()=>startPoemPlay(1));await p.waitForFunction(()=>_audioEl&&!_audioEl.paused&&_audioEl.currentTime>.02);});
