const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let browser;before(async()=>browser=await pw.chromium.launch({headless:true,args:['--mute-audio'],channel:'msedge'}));after(async()=>browser?.close());
async function setup(t){const c=await browser.newContext(),p=await c.newPage();await p.goto('http://127.0.0.1:5173/');await p.waitForTimeout(650);await p.evaluate(()=>{closeModal();state.audio.muted=true;BADGES_DEF.forEach(b=>state.badges[b.id]=1);});await p.clock.install();t.after(()=>c.close());return p;}
test('correct answers display 3, 2, 1 seconds then advance exactly once',async t=>{const p=await setup(t);await p.evaluate(()=>{startChallenge('make');answerChallenge(_challenge.question.options.indexOf(_challenge.question.answer));});assert.match(await p.locator('[data-auto-next]').innerText(),/3s/);await p.clock.fastForward(1000);assert.match(await p.locator('[data-auto-next]').innerText(),/2s/);await p.clock.fastForward(1000);assert.match(await p.locator('[data-auto-next]').innerText(),/1s/);await p.clock.fastForward(999);assert.equal(await p.evaluate(()=>_challenge.index),0);await p.clock.fastForward(1);assert.equal(await p.evaluate(()=>_challenge.index),1);await p.clock.fastForward(6000);assert.equal(await p.evaluate(()=>_challenge.index),1);});
test('manual next cancels pending automatic next and closing cancels reopening',async t=>{const p=await setup(t);await p.evaluate(()=>{startChallenge('make');answerChallenge(_challenge.question.options.indexOf(_challenge.question.answer));});await p.locator('[data-auto-next]').click();await p.clock.fastForward(4000);assert.equal(await p.evaluate(()=>_challenge.index),1);await p.evaluate(()=>{answerChallenge(_challenge.question.options.indexOf(_challenge.question.answer));closeModal();startLetterPlay('listen');});await p.clock.fastForward(4000);assert.equal(await p.locator('#letterPlay').count(),1);assert.equal(await p.evaluate(()=>_letterPlay.index),0);});
test('wrong answers do not start a countdown and rewards do not repeat',async t=>{const p=await setup(t);await p.evaluate(()=>{startLetterPlay('listen');answerLetterPlay((_letterPlay.answer+1)%3);});assert.equal(await p.locator('[data-auto-next]').count(),0);await p.clock.fastForward(4000);assert.equal(await p.evaluate(()=>_letterPlay.index),0);await p.evaluate(()=>{answerLetterPlay(_letterPlay.answer);answerLetterPlay(_letterPlay.answer);});await p.clock.fastForward(3000);assert.equal(await p.evaluate(()=>_letterPlay.index),1);assert.equal(await p.evaluate(()=>state.practice.progress.letters_listen),1);});
test('praise is recorded, once per question, and never queues native speech',async t=>{const p=await setup(t);await p.evaluate(()=>{state.audio.muted=false;window.nativeCalls=0;window.recordedCalls=0;synth={speak:()=>nativeCalls++,cancel(){},speaking:false,pending:false};playRecordedClips=()=>recordedCalls++;showModal('test');celebrate();celebrate();celebrate();});assert.equal(await p.evaluate(()=>nativeCalls),0);assert.equal(await p.evaluate(()=>recordedCalls),1);await p.evaluate(()=>{showModal('new question');celebrate();});assert.equal(await p.evaluate(()=>recordedCalls),2);});
test('stop clears native queues even when the host reports no pending speech',async t=>{const p=await setup(t);assert.equal(await p.evaluate(()=>{var canceled=0;synth={speaking:false,pending:false,cancel:()=>canceled++};stopSpeak();return canceled;}),1);});
test('sorting automatically checks complete selections and alternates all four dimensions',async t=>{const p=await setup(t);await p.evaluate(()=>startLogicSort());assert.equal(await p.getByRole('button',{name:'检查顺序',exact:true}).count(),0);const seen=[];for(let i=0;i<10;i++){seen.push(await p.evaluate(()=>_logicSort.dimension));await p.evaluate(()=>_logicSort.values.forEach(pickLogicSort));assert.equal(await p.evaluate(()=>_logicSort.solved),true);assert.match(await p.locator('[data-auto-next]').innerText(),/3s/);await p.clock.fastForward(3000);}assert.deepEqual(seen,['size','length','height','quantity','size','length','height','quantity','size','length']);assert.equal(await p.evaluate(()=>state.practice.progress.logic_sort_mixed),10);assert.equal(await p.locator('#logicSort').count(),0);});
test('wrong sorting stays for retry, and mixed round resumes after refresh',async t=>{const p=await setup(t);await p.evaluate(()=>{startLogicSort();_logicSort.values.slice().reverse().forEach(pickLogicSort);});assert.equal(await p.evaluate(()=>_logicSort.solved),false);assert.equal(await p.locator('[data-auto-next]').count(),0);await p.clock.fastForward(4000);assert.equal(await p.evaluate(()=>_logicSort.index),0);await p.evaluate(()=>{resetLogicSort();_logicSort.values.forEach(pickLogicSort);closeModal();});await p.reload();await p.evaluate(()=>startLogicSort());assert.equal(await p.evaluate(()=>_logicSort.index),1);assert.equal(await p.evaluate(()=>_logicSort.dimension),'length');});
