const {test,before,after}=require('node:test');
const assert=require('node:assert/strict'),path=require('node:path');
const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let browser;before(async()=>browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:'msedge'}));after(async()=>browser?.close());
async function setup(t){const c=await browser.newContext(),p=await c.newPage();await p.goto('http://127.0.0.1:5173/');await p.waitForTimeout(650);await p.evaluate(()=>{closeModal();state.audio.muted=true;BADGES_DEF.forEach(b=>state.badges[b.id]=1);});t.after(()=>c.close());return p;}
test('letter listening and word pictures each finish ten varied questions',async t=>{const p=await setup(t);const result=await p.evaluate(()=>{const out=[];for(const kind of ['listen','words']){startLetterPlay(kind);const seen=new Set();for(let i=0;i<10;i++){seen.add(_letterPlay.target.upper);const q=_letterPlay;answerLetterPlay((q.answer+1)%q.options.length);if(q.solved)throw Error('Wrong answer accepted');answerLetterPlay(q.answer);answerLetterPlay(q.answer);nextLetterPlay();}out.push([kind,state.practice.progress['letters_'+kind],seen.size]);}return out;});assert.deepEqual(result.map(r=>r[1]),[10,10]);assert.ok(result.every(r=>r[2]>=5));});
test('poem practice gives ten activities and works for every poem',async t=>{const p=await setup(t);const result=await p.evaluate(()=>{const out=[];for(const poem of POEMS){startPoemPlay(poem.id);for(let i=0;i<10;i++){const q=_poemPlay;if(q.index<4)confirmPoemLine();else answerPoemPlay(q.answer);nextPoemPlay();}out.push(state.practice.progress['poem_'+poem.id]);}return out;});assert.equal(result.length,20);assert.ok(result.every(n=>n===10));});
test('poem and letter progress survives reload, with no duplicate answer credit',async t=>{const p=await setup(t);await p.evaluate(()=>{startPoemPlay(1);confirmPoemLine();confirmPoemLine();closeModal();startLetterPlay('listen');answerLetterPlay(_letterPlay.answer);closeModal();});await p.reload();await p.evaluate(()=>startPoemPlay(1));assert.equal(await p.evaluate(()=>_poemPlay.index),1);await p.evaluate(()=>startLetterPlay('listen'));assert.equal(await p.evaluate(()=>_letterPlay.index),1);});
test('poem and letter activities fit a short phone at every stage',async t=>{const p=await setup(t);await p.setViewportSize({width:375,height:667});const bad=await p.evaluate(()=>{const bad=[];function check(name){const m=document.getElementById('modal');if(m.scrollHeight>m.clientHeight+2||m.scrollWidth>m.clientWidth+2)bad.push(name);}for(const poem of POEMS){startPoemPlay(poem.id);for(let i=0;i<10;i++){check(poem.t+i);if(i<4)confirmPoemLine();else answerPoemPlay(_poemPlay.answer);check(poem.t+i+' answered');nextPoemPlay();}}for(const kind of ['listen','words']){startLetterPlay(kind);check(kind);answerLetterPlay(_letterPlay.answer);check(kind+' answered');}return bad;});assert.deepEqual(bad,[]);});
test('word and sentence reading offer ten exercises with parent confirmation and saved progress',async t=>{const p=await setup(t);await p.setViewportSize({width:375,height:667});const result=await p.evaluate(()=>{const bad=[];for(const kind of ['word','sentence']){if(kind==='word')startReadAlong('animals');else startSentenceRead(0);for(let i=0;i<10;i++){const value=kind==='word'?ENGLISH.themes.find(t=>t.id==='animals').words[i].w:i;confirmParentRead(kind,value);confirmParentRead(kind,value);const modal=document.getElementById('modal');if(modal.scrollHeight>modal.clientHeight+2)bad.push(kind+i);document.querySelector('#modal .modal-actions .btn-green').click();}}return {bad,words:state.practice.progress.english_read_animals,sentences:state.practice.progress.english_sentence_read};});assert.deepEqual(result,{bad:[],words:10,sentences:10});});
test('adventure respects math range and all questions fit with working listening prompts',async t=>{const p=await setup(t);await p.setViewportSize({width:375,height:667});const bad=await p.evaluate(()=>{const bad=[];for(let n=1;n<=10;n++){startLevel(n,true);for(let i=0;i<10;i++){_levelData.current=i;showLevelQuestion();const q=_levelData.questions[i],m=document.getElementById('modal');if(m.scrollHeight>m.clientHeight+2||m.scrollWidth>m.clientWidth+2)bad.push('overflow '+n+':'+i);if(!recordedSpeechClips(q.q,'child'))bad.push('audio '+q.q);if(q.type==='math'&&+q.answer>5)bad.push('range '+q.q);if(q.type==='poem'&&q.q.includes('谁写'))bad.push('too advanced');}}return bad;});assert.deepEqual(bad,[]);});
test('adventure renders a dragonfly picture instead of a mosquito',async t=>{const p=await setup(t);await p.evaluate(()=>{startLevel(1,true);_levelData.questions[0]={type:'poem',q:'停在小荷上的是谁？',answer:'🦟 蜻蜓',options:['🦟 蜻蜓','🦋 蝴蝶','🐞 瓢虫']};showLevelQuestion();});assert.equal(await p.locator('#modal svg[aria-label="蜻蜓"]').count(),1);assert.ok(!(await p.locator('#modal').innerText()).includes('🦟'));});
