const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
let browser;
before(async()=>{browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:process.env.BROWSER_CHANNEL||'msedge'});});
after(async()=>{await browser?.close();});
async function setup(t){const context=await browser.newContext();const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');await p.waitForTimeout(600);await p.evaluate(()=>{closeModal();state.firstVisit=false;BADGES_DEF.forEach(b=>state.badges[b.id]=1);saveState();});t.after(async()=>{await context.close();assert.deepEqual(errors,[]);});return p;}
test('memory game exposes only two unmatched cards and unlocks after mismatch',async t=>{const p=await setup(t);await p.evaluate(()=>{startShapeMatch();const groups={};document.querySelectorAll('[data-shape]').forEach(b=>(groups[b.dataset.shape]??=[]).push(b));const pairs=Object.values(groups);[pairs[0][0],pairs[1][0],pairs[0][1],pairs[1][1]].forEach(b=>b.click());});assert.equal(await p.locator('[data-shape][data-flipped="1"]').count(),2);await p.waitForTimeout(900);assert.equal(await p.locator('[data-shape][data-flipped="1"]').count(),0);await p.evaluate(()=>{const groups={};document.querySelectorAll('[data-shape]').forEach(b=>(groups[b.dataset.shape]??=[]).push(b));Object.values(groups).forEach(pair=>pair.forEach(b=>{b.click();b.click();}));});assert.equal(await p.evaluate(()=>state.practice.progress.logic_memory_pairs),3);assert.equal(await p.evaluate(()=>state.logic.completed.length),0);assert.equal(await p.evaluate(()=>state.stars),0);});
test('manual spelling reset cancels the previous failed attempt timer',async t=>{const p=await setup(t);await p.evaluate(()=>{const random=Math.random;let first=true;Math.random=()=>{if(first){first=false;return 0;}return random();};startSpellChallenge('animals');Math.random=random;const buttons=[...document.querySelectorAll('[data-l]')];const wrong=buttons.filter(b=>!['c','a','t'].includes(b.dataset.l));wrong.slice(0,3).forEach(b=>b.click());[...document.querySelectorAll('#modal button')].find(b=>b.textContent==='重置').click();document.querySelector('[data-l="c"]').click();});await p.waitForTimeout(1100);assert.equal(await p.locator('[id$="_answer"]').innerText(),'c');await p.evaluate(()=>{for(const l of 'at')document.querySelector('[data-l="'+l+'"]').click();});assert.equal(await p.evaluate(()=>state.stars),3);});
test('spelling waits for failed answer reset before accepting more tiles',async t=>{const p=await setup(t);await p.evaluate(()=>{startSpellChallenge('animals');const target=_spellTarget;const tiles=[...document.querySelectorAll('[data-l]')];const wrong=tiles.filter(b=>!target.includes(b.dataset.l));wrong.forEach(b=>b.click());tiles.forEach(b=>b.click());});assert.equal(await p.evaluate(()=>_spellPicked.length),await p.evaluate(()=>_spellTarget.length));});
test('transcription matching respects letter order and ignores punctuation',async t=>{const p=await setup(t);const r=await p.evaluate(()=>({wrong:calcSimilarity('good','dog'),sentenceWrong:calcSimilarity('Good night','Good morning'),exact:calcSimilarity(' Hello, DOG! ','hello dog')}));assert.ok(r.wrong<0.6);assert.ok(r.sentenceWrong<0.8);assert.equal(r.exact,1);});
test('readalong rejects a different word and labels recognition without pronunciation scores',async t=>{const p=await setup(t);await p.evaluate(()=>{startReadAlong('animals');startRecognition=cb=>{cb('good');return true;};doReadAlong('dog');});assert.equal(await p.evaluate(()=>state.stars),0);await p.evaluate(()=>{startRecognition=cb=>{cb('dog');return true;};doReadAlong('dog');doReadAlong('dog');});assert.equal(await p.evaluate(()=>state.stars),2);assert.ok(!(await p.locator('#readResult').innerText()).includes('%'));assert.ok((await p.locator('#modal').innerText()).includes('发音评分'));});
test('sentence readalong rejects a different sentence and rewards one exercise once',async t=>{const p=await setup(t);await p.evaluate(()=>{startSentenceRead(3);startRecognition=cb=>{cb('good night');return true;};doSentenceRead(3);});assert.equal(await p.evaluate(()=>state.stars),0);await p.evaluate(()=>{startRecognition=cb=>{cb('Good morning!');return true;};doSentenceRead(3);doSentenceRead(3);});assert.equal(await p.evaluate(()=>state.stars),2);assert.ok((await p.locator('#modal').innerText()).includes('发音评分'));});
test('theme medal is earned when final word is learned and persists after reload',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('english');enterEnglishTheme('animals');const words=ENGLISH.themes.find(t=>t.id==='animals').words;words.forEach(w=>markLearned(w.w));});assert.ok(await p.evaluate(()=>state.english.themeStars.animals));await p.reload();assert.ok(await p.evaluate(()=>state.english.themeStars.animals));});
test('unavailable recognition offers explicit parent confirmation without duplicate awards',async t=>{const p=await setup(t);await p.evaluate(()=>{recognition=null;startReadAlong('animals');doReadAlong('dog');});await p.getByRole('button',{name:'孩子已跟读 · 家长确认',exact:true}).click();await p.evaluate(()=>confirmParentRead('word','dog'));assert.equal(await p.evaluate(()=>state.stars),2);assert.ok((await p.locator('#readStatus').innerText()).includes('家长'));assert.equal(await p.evaluate(()=>state.practice.progress.english_read_animals),1);});
