const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
let browser;
before(async()=>{browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:process.env.BROWSER_CHANNEL||'msedge'});});
after(async()=>{await browser?.close();});
async function setup(t){const context=await browser.newContext();const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');await p.waitForTimeout(600);await p.evaluate(()=>{closeModal();state.audio.muted=true;state.firstVisit=false;BADGES_DEF.forEach(b=>state.badges[b.id]=1);saveState();const timeout=modalTimeout;window.roundTransitions=[];modalTimeout=(fn,delay)=>delay>=1000?(roundTransitions.push(fn),0):timeout(fn,delay);});t.after(async()=>{await context.close();assert.deepEqual(errors,[]);});return p;}
const games=[
  {key:'letters_match',start:'startLetterMatch()',selector:'#letterOptions',answer:()=>{const b=[...document.querySelectorAll('#letterOptions button')].find(b=>{const a=b.getAttribute('onclick').match(/\((.*)\)/)[1].split(',');return a[0]===a[1];});b.click();b.click();}},
  {key:'logic_memory',start:'startShapeMatch()',selector:'[data-shape]',answer:()=>{const groups={};document.querySelectorAll('[data-shape]').forEach(b=>(groups[b.dataset.shape]??=[]).push(b));Object.values(groups).forEach(pair=>pair.forEach(b=>{b.click();b.click();}));}},
  {key:'english_listen_animals',start:'startListenPick("animals")',selector:'[data-w]',answer:()=>{const b=[...document.querySelectorAll('[data-w]')].find(b=>{const a=b.getAttribute('onclick').match(/\((.*)\)/)[1].split(',');return a[1]===a[2];});b.click();b.click();}},
  {key:'english_spell_animals',start:'startSpellChallenge("animals")',selector:'[data-l]',answer:()=>{for(const l of _spellTarget){const b=[...document.querySelectorAll('[data-l]')].find(b=>b.dataset.l===l&&b.style.visibility!=='hidden');b.click();}}},
  {key:'english_sentence_fill',start:'startSentenceFill(0)',selector:'[id^="sf"]',answer:()=>{const b=[...document.querySelectorAll('#modal .option-btn')].find(b=>{const a=b.getAttribute('onclick').match(/\((.*)\)/)[1].split(',');return a[1]===a[2];});b.click();b.click();}}
];
for(const game of games)test(game.key+' completes exactly ten questions and starts a new round explicitly',async t=>{const p=await setup(t);await p.evaluate(source=>eval(source),game.start);for(let n=1;n<=10;n++){await p.evaluate(game.answer);assert.equal(await p.evaluate(key=>state.practice.progress[key],game.key),n);await p.evaluate(()=>{const next=roundTransitions.shift();if(!next)throw Error('Missing next-question transition');next();});}assert.equal(await p.locator(game.selector).count(),0);assert.equal(await p.evaluate(key=>state.practice.progress[key],game.key),10);await p.evaluate(source=>eval(source),game.start);assert.equal(await p.evaluate(key=>state.practice.progress[key],game.key),0);});
test('letter review remains available after all 26 letters are mastered',async t=>{const p=await setup(t);await p.evaluate(()=>{state.letters.matched=LETTERS_DATA.map(l=>l.upper);startLetterMatch();});assert.equal(await p.locator('#letterOptions button').count(),3);});
test('listening round resumes saved progress without depending on active theme navigation',async t=>{const p=await setup(t);await p.evaluate(()=>startListenPick('animals'));await p.evaluate(games[2].answer);assert.equal(await p.evaluate(()=>state.practice.progress.english_listen_animals),1);await p.reload();await p.evaluate(()=>{closeModal();startListenPick('animals');});assert.equal(await p.evaluate(()=>state.practice.progress.english_listen_animals),1);});
test('every generated adventure level has ten questions',async t=>{const p=await setup(t);assert.deepEqual(await p.evaluate(()=>Array.from({length:10},(_,i)=>generateLevelQuestions(i+1).length)),Array(10).fill(10));});
test('adventure answers and generated questions survive closing during feedback and reload',async t=>{const p=await setup(t);const original=await p.evaluate(()=>{switchTab('levels');startLevel(1);return JSON.stringify(_levelData.questions);});await p.evaluate(()=>{for(let i=0;i<3;i++){const q=_levelData.questions[_levelData.current];[...document.querySelectorAll('#modal .option-btn')].find(b=>b.dataset.val===String(q.answer)).click();if(i<2)roundTransitions.shift()();}closeModal();startLevel(1);});assert.equal(await p.evaluate(()=>_levelData.current),3);await p.reload();await p.evaluate(()=>{closeModal();startLevel(1);});assert.equal(await p.evaluate(()=>_levelData.current),3);assert.equal(await p.evaluate(()=>_levelData.correct),3);assert.equal(await p.evaluate(()=>JSON.stringify(_levelData.questions)),original);assert.ok((await p.locator('#modal').innerText()).includes('4/10题'));});
test('final adventure answer settles once even when closed before the result timer',async t=>{const p=await setup(t);await p.evaluate(()=>{startLevel(1);for(let i=0;i<10;i++){const q=_levelData.questions[_levelData.current];const b=[...document.querySelectorAll('#modal .option-btn')].find(b=>b.dataset.val===String(q.answer));b.click();b.click();if(i<9)roundTransitions.shift()();}closeModal();});assert.equal(await p.evaluate(()=>state.stars),30);assert.deepEqual(await p.evaluate(()=>state.levels.completed),[1]);await p.reload();await p.evaluate(()=>{closeModal();startLevel(1);startLevel(1);});assert.equal(await p.evaluate(()=>state.stars),30);assert.ok((await p.locator('#modal').innerText()).includes('10/10'));await p.getByRole('button',{name:'再玩一轮',exact:true}).click();assert.equal(await p.evaluate(()=>_levelData.current),0);assert.equal(await p.evaluate(()=>state.stars),30);});
test('saved adventure sessions validate counts and preserve old-backup defaults',async t=>{const p=await setup(t);assert.deepEqual(await p.evaluate(()=>normalizeState({stars:3}).levels.sessions),{});assert.equal(await p.evaluate(()=>{startLevel(1);const backup=JSON.parse(JSON.stringify(state));backup.levels.sessions[1].correct=11;try{normalizeState(backup);return false;}catch{return true;}}),true);});
