const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
let browser;
before(async()=>{browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:process.env.BROWSER_CHANNEL||'msedge'});});
after(async()=>{await browser?.close();});
async function setup(t){const context=await browser.newContext();const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');await p.waitForTimeout(600);await p.evaluate(()=>{closeModal();state.firstVisit=false;saveState();});t.after(async()=>{await context.close();assert.deepEqual(errors,[],'browser runtime errors');});return p;}
async function quietBadges(p){await p.evaluate(()=>BADGES_DEF.forEach(b=>state.badges[b.id]=1));}
async function importJSON(p,data){await p.locator('#importFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await p.waitForTimeout(150);}
test('seven modules render and backup controls survive navigation',async t=>{const p=await setup(t);await p.waitForTimeout(2600);for(const tab of ['letters','poems','numbers','logic','levels','english','stories']){await p.locator(`#sidebar [onclick="switchTab('${tab}')"]`).click();assert.ok(await p.locator('#main .section-title').count());assert.equal(await p.locator('#backupBar').count(),1,tab+' missing backup');}});
test('audio can be muted, changed to zero and stopped on modal close',async t=>{const p=await setup(t);await p.evaluate(()=>{showModal('audio test');playAudio('audio/letter_A.mp3','A','en');});await p.waitForFunction(()=>_audioEl&&!_audioEl.paused);await p.evaluate(()=>setVolume(0));assert.equal(await p.locator('#volRange').inputValue(),'0');assert.equal(await p.evaluate(()=>_audioEl.volume),0);await p.evaluate(()=>{setVolume(80);toggleMute();});assert.ok(await p.evaluate(()=>_audioEl.paused||_audioEl.muted||_audioEl.volume===0));await p.evaluate(()=>{toggleMute();playAudio('audio/letter_A.mp3','A','en');closeModal();});assert.equal(await p.evaluate(()=>_audioEl.paused),true);});
test('flashcard advances and is learned only on explicit action',async t=>{const p=await setup(t);await quietBadges(p);await p.evaluate(()=>{switchTab('english');enterEnglishTheme('animals');startFlashcard('animals');});assert.equal(await p.locator('.fc-en').innerText(),'cat');assert.equal(await p.evaluate(()=>!!state.english.learned.cat),false);await p.getByRole('button',{name:'下一个 →',exact:true}).click();assert.equal(await p.locator('.fc-en').innerText(),'dog');await p.getByRole('button',{name:'学会了 ⭐',exact:true}).click();assert.equal(await p.evaluate(()=>state.english.learned.dog),true);});
test('every spelling word has all required letters including repeats',async t=>{const p=await setup(t);const failures=await p.evaluate(()=>{const failures=[];const random=Math.random;for(const theme of ENGLISH.themes){for(let i=0;i<theme.words.length;i++){if(!/^[a-z]{1,8}$/.test(theme.words[i].w))continue;let first=true;Math.random=()=>{if(first){first=false;const pool=theme.words.filter(w=>/^[a-z]{1,8}$/.test(w.w));return(pool.indexOf(theme.words[i])+0.2)/pool.length;}return random();};startSpellChallenge(theme.id);const available=[...document.querySelectorAll('#modal [data-l]')].map(b=>b.dataset.l);for(const l of theme.words[i].w){const at=available.indexOf(l);if(at<0){failures.push(theme.words[i].w+': missing '+l);break;}available.splice(at,1);}}}Math.random=random;return failures;});assert.deepEqual(failures,[]);});
test('quantity sorting rejects descending order and accepts ascending order',async t=>{const p=await setup(t);await quietBadges(p);await p.evaluate(()=>{switchTab('logic');startLogicSort('quantity');[...document.querySelectorAll('[data-sort-value]')].sort((a,b)=>+b.dataset.sortValue-+a.dataset.sortValue).forEach(b=>b.click());checkLogicSort();});assert.equal(await p.evaluate(()=>state.logic.completed.length),0);await p.evaluate(()=>{resetLogicSort();[...document.querySelectorAll('[data-sort-value]')].sort((a,b)=>+a.dataset.sortValue-+b.dataset.sortValue).forEach(b=>b.click());checkLogicSort();});assert.equal(await p.evaluate(()=>state.logic.completed.length),1);});
test('pattern clues contain a visible repeated cycle at all difficulties',async t=>{const p=await setup(t);const results=await p.evaluate(()=>[0,1,2].map(level=>{state.logic.level=level;startPattern();return _logicPattern.sequence.length>=2*_logicPattern.cycle.length;}));assert.deepEqual(results,[true,true,true]);});
test('exiting after an answer cancels automatic reopening',async t=>{const p=await setup(t);await quietBadges(p);await p.evaluate(()=>{switchTab('numbers');startMathQuiz();const b=[...document.querySelectorAll('#modal .option-btn')].find(b=>+b.dataset.val===_mathQ.answer);b.click();closeModal();switchTab('poems');});await p.waitForTimeout(2400);assert.equal(await p.locator('#modal-overlay').evaluate(e=>e.classList.contains('show')),false);});
test('clear data preserves valid audio settings and reloads normally',async t=>{const p=await setup(t);await p.evaluate(()=>doClearData());assert.deepEqual(await p.evaluate(()=>state.audio),{volume:0.8,muted:false});await p.reload();await p.waitForTimeout(650);assert.equal(await p.locator('#sidebar .nav-item').count(),8);});
test('partial backup restores defaults and synchronizes navigation and audio',async t=>{const p=await setup(t);await importJSON(p,{stars:7,currentTab:'numbers',audio:{volume:0,muted:true},letters:{matched:['A']}});assert.equal(await p.locator('#starCount').innerText(),'7');assert.equal(await p.locator('#sidebar .active').innerText(),'🔢\n数字王国');assert.equal(await p.locator('#volRange').inputValue(),'0');await p.evaluate(()=>switchTab('letters'));assert.ok((await p.locator('#main').innerText()).includes('1/26'));});
test('malformed backup does not overwrite valid progress',async t=>{const p=await setup(t);await p.evaluate(()=>{state.stars=17;saveState();});await importJSON(p,{stars:2,letters:null});assert.equal(await p.evaluate(()=>state.stars),17);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem(STORAGE_KEY)).stars),17);});
test('story continuous playback starts even when auto-read is off',async t=>{const p=await setup(t);await quietBadges(p);await p.evaluate(()=>{switchTab('stories');state.stories.autoRead=false;showStory(STORIES[0].id);toggleAutoPlay();});assert.ok(await p.evaluate(()=>_audioEl&&_audioEl.src.endsWith(recordedSpeechClips(STORIES[0].p[0],'story')[0])));});
test('first achievement does not replace the current exercise',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('english');startFlashcard('animals');markLearned('cat');});assert.equal(await p.locator('#fc').count(),1);assert.ok(await p.evaluate(()=>state.badges.first_star));});
test('keyboard activation cannot score the same answer twice',async t=>{const p=await setup(t);await quietBadges(p);await p.evaluate(()=>{startMathQuiz();const b=[...document.querySelectorAll('#modal .option-btn')].find(b=>+b.dataset.val===_mathQ.answer);b.click();b.click();});assert.equal(await p.evaluate(()=>state.numbers.quizDone),1);assert.equal(await p.evaluate(()=>state.stars),2);});
test('speech recognition failure restores retryable status',async t=>{const p=await setup(t);await p.evaluate(()=>{recognition=null;startReadAlong('animals');doReadAlong('cat');});assert.ok(!(await p.locator('#readStatus').innerText()).includes('正在聆听'));});
test('referenced audio files exist',async t=>{const p=await setup(t);const files=await p.evaluate(()=>[...LETTERS_DATA.map(l=>'letter_'+l.upper+'.mp3'),...Array.from({length:21},(_,i)=>'num_'+i+'.mp3'),...POEMS.map(p=>'poem_'+p.id+'.mp3'),...STORIES.flatMap(s=>s.p.map((_,i)=>'story_'+s.id+'_'+i+'.mp3')),...SENTENCES.map((_,i)=>'sen_'+i+'.mp3'),...ENGLISH.themes.flatMap(t=>t.words.map(w=>recordedSpeechClips(w.w,'en')[0].replace(/^audio\//,'')))]);assert.deepEqual(files.filter(f=>!fs.existsSync(path.join(__dirname,'audio',f))),[]);});
test('mobile navigation renders without horizontal page overflow',async t=>{const p=await setup(t);await p.setViewportSize({width:390,height:844});assert.equal(await p.locator('#bottomNav').isVisible(),true);for(const tab of ['letters','poems','numbers','logic','levels','english','stories']){await p.evaluate(tab=>switchTab(tab),tab);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),tab+' overflow');}});
test('letter, counting, pattern, listening and sentence quizzes can be answered',async t=>{const p=await setup(t);for(const start of ['startLetterMatch()','startCountGame()','startPattern()','switchTab("english");enterEnglishTheme("animals");startListenPick("animals")','startSentenceFill(2)']){await p.evaluate(source=>{closeModal();eval(source);},start);const before=await p.evaluate(()=>state.stars);await p.evaluate(()=>{const buttons=[...document.querySelectorAll('#modal .option-btn')];const correct=buttons.find(b=>{const args=b.getAttribute('onclick').match(/\((.*)\)/)[1].split(',').map(v=>v.trim().replace(/^'|'$/g,''));return args[args.length-2]===args[args.length-1]||(b.dataset.lower&&args[0]===args[1]);});if(!correct)throw Error('No correct option');correct.click();});assert.ok(await p.evaluate(n=>state.stars>n,before),start);}});
test('wrong math answer allows retry, then advances to a fresh question',async t=>{const p=await setup(t);await p.evaluate(()=>{startMathQuiz();[...document.querySelectorAll('#modal .option-btn')].find(b=>+b.dataset.val!==_mathQ.answer).click();});assert.equal(await p.evaluate(()=>state.stars),0);await p.waitForTimeout(900);await p.evaluate(()=>[...document.querySelectorAll('#modal .option-btn')].find(b=>+b.dataset.val===_mathQ.answer).click());assert.equal(await p.evaluate(()=>state.numbers.quizDone),1);await p.waitForTimeout(2150);assert.equal(await p.locator('#modal .option-btn:enabled').count(),4);});
test('all ten level questions lead to one completion and unlock level two',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('levels');startLevel(1);});for(let i=0;i<10;i++){await p.evaluate(()=>{const answer=String(_levelData.questions[_levelData.current].answer);[...document.querySelectorAll('#modal .option-btn')].find(b=>b.dataset.val===answer).click();});await p.getByRole('button',{name:'下一题',exact:true}).click();}assert.deepEqual(await p.evaluate(()=>state.levels.completed),[1]);assert.equal(await p.evaluate(()=>state.stars),30);await p.getByRole('button',{name:'太棒了！',exact:true}).click();assert.equal(await p.locator('.level-node.available').count(),1);});
test('spelling banana consumes each repeated tile and awards once',async t=>{const p=await setup(t);await p.evaluate(()=>{let first=true;const random=Math.random;Math.random=()=>{if(first){first=false;return 1.2/ENGLISH.themes.find(t=>t.id==='fruits').words.filter(w=>/^[a-z]{1,8}$/.test(w.w)).length;}return random();};startSpellChallenge('fruits');Math.random=random;for(const letter of 'banana'){const b=[...document.querySelectorAll('#modal [data-l]')].find(b=>b.dataset.l===letter&&b.style.visibility!=='hidden');b.click();}});assert.equal(await p.evaluate(()=>state.english.learned.banana),true);assert.equal(await p.evaluate(()=>state.stars),3);});
test('shape matching and numeric ordering complete',async t=>{const p=await setup(t);await p.evaluate(()=>{startShapeMatch();const groups={};document.querySelectorAll('#modal [data-shape]').forEach(b=>(groups[b.dataset.shape]??=[]).push(b));Object.values(groups).forEach(pair=>pair.forEach(b=>b.click()));});assert.equal(await p.evaluate(()=>state.practice.progress.logic_memory_pairs),3);assert.equal(await p.evaluate(()=>state.logic.completed.length),0);await p.evaluate(()=>{closeModal();startOrderGame();[...document.querySelectorAll('#modal .option-btn')].sort((a,b)=>+a.dataset.val- +b.dataset.val).forEach(b=>b.click());});assert.equal(await p.evaluate(()=>state.numbers.orderDone),1);});
test('stories support favorites, page navigation, quiz and night mode',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('stories');showStory(STORIES[0].id);});const first=await p.locator('#storyText').innerText();await p.getByRole('button',{name:'☆ 收藏',exact:true}).click();assert.equal(await p.evaluate(()=>state.stories.favorites.length),1);await p.getByRole('button',{name:'下一页 →',exact:true}).click();assert.notEqual(await p.locator('#storyText').innerText(),first);await p.getByRole('button',{name:'← 上一页',exact:true}).click();assert.equal(await p.locator('#storyText').innerText(),first);await p.evaluate(()=>{const s=STORIES[0];while(state.stories.currentPage<s.p.length-1)nextStoryPage();showStoryQuiz(s.id);answerReading(_reading.question.answer);closeModal();toggleNightMode();});assert.equal(await p.locator('body').evaluate(b=>b.classList.contains('night')),true);});
test('backup export and reimport round trip preserves progress',async t=>{const p=await setup(t);await p.evaluate(()=>{state.stars=23;state.poems.favorites=[POEMS[0].id];saveState();openParentTools();});const downloading=p.waitForEvent('download');await p.locator('#modal').getByRole('button',{name:'💾 导出备份',exact:true}).click();const download=await downloading;const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(backup.stars,23);await p.evaluate(()=>doClearData());await importJSON(p,backup);assert.equal(await p.evaluate(()=>state.stars),23);assert.equal(await p.evaluate(()=>state.poems.favorites.length),1);await p.reload();assert.equal(await p.locator('#starCount').innerText(),'23');});
test('new quiz is not closed by the previous answered quiz timer',async t=>{const p=await setup(t);await p.evaluate(()=>{startMathQuiz();[...document.querySelectorAll('#modal .option-btn')].find(b=>+b.dataset.val===_mathQ.answer).click();startSentenceFill(0);});await p.waitForTimeout(2400);assert.ok((await p.locator('#modal').innerText()).includes('_____'));assert.equal(await p.locator('#modal-overlay').evaluate(e=>e.classList.contains('show')),true);});
test('last letter match awards its completion badge immediately',async t=>{const p=await setup(t);await p.evaluate(()=>{state.letters.matched=LETTERS_DATA.slice(0,25).map(l=>l.upper);startLetterMatch();document.querySelector('#letterOptions [data-lower="z"]').click();});assert.ok(await p.evaluate(()=>state.badges.letter_master));});
test('story question alone does not award completion stars',async t=>{const p=await setup(t);await p.evaluate(()=>{showStoryQuiz(STORIES[0].id);answerReading(_reading.question.answer);answerReading(_reading.question.answer);});assert.equal(await p.evaluate(()=>state.stars),0);});
test('reset after successful spelling cannot award the same word twice',async t=>{const p=await setup(t);await p.evaluate(()=>{let first=true;const random=Math.random;Math.random=()=>{if(first){first=false;return 0;}return random();};startSpellChallenge('animals');Math.random=random;const answer=()=>{for(const l of 'cat'){const b=[...document.querySelectorAll('#modal [data-l]')].find(b=>b.dataset.l===l&&b.style.visibility!=='hidden');if(b)b.click();}};answer();[...document.querySelectorAll('#modal button')].find(b=>b.textContent==='重置').click();answer();});assert.equal(await p.evaluate(()=>state.stars),3);});
