const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
let browser;
before(async()=>{browser=await pw.chromium.launch({headless:true,args:["--mute-audio"],channel:'msedge'});});
after(async()=>{await browser?.close();});
async function setup(t){const context=await browser.newContext();const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173/');await p.waitForTimeout(600);await p.evaluate(()=>{closeModal();state.firstVisit=false;BADGES_DEF.forEach(b=>state.badges[b.id]=1);saveState();});t.after(async()=>{await context.close();assert.deepEqual(errors,[]);});return p;}
test('math replaces recognition with gentle ten-question challenges and saves difficulty',async t=>{const p=await setup(t);await p.evaluate(()=>switchTab('numbers'));assert.ok(!(await p.locator('#main').innerText()).includes('数字认知'));await p.getByRole('button',{name:'试一试 · 10以内',exact:true}).click();await p.getByRole('button',{name:'开始合起来与拿走',exact:true}).click();for(let i=0;i<10;i++){await p.evaluate(()=>answerChallenge(_challenge.question.options.indexOf(_challenge.question.answer)));await p.getByRole('button',{name:i===9?'查看结果':'下一题',exact:true}).click();}assert.equal(await p.evaluate(()=>state.numbers.challengeDone),1);assert.ok((await p.locator('#modal').innerText()).includes('10 / 10'));await p.reload();assert.equal(await p.evaluate(()=>state.numbers.difficulty),1);assert.equal(await p.evaluate(()=>state.numbers.challengeDone),1);});
test('math generators stay within the selected range',async t=>{const p=await setup(t);const failures=await p.evaluate(()=>{const out=[];for(let level=0;level<2;level++)for(const kind of ['combine','make','compare','pattern'])for(let i=0;i<60;i++){const q=makeChallengeQuestion(kind,level);if(q.options.length!==3||new Set(q.options).size!==3||!q.options.includes(q.answer)||q.quantities.some(n=>n<0||n>(level?10:5)))out.push({kind,level,q});}return out;});assert.deepEqual(failures,[]);});
test('english lesson retries listening and finishes with parent-assisted speaking',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('english');startEnglishLesson(0);});await p.getByRole('button',{name:'听好了，选一选',exact:true}).click();await p.evaluate(()=>answerLesson((_lesson.question.answer+1)%3));assert.equal(await p.evaluate(()=>Object.keys(state.english.review).length),1);assert.equal(await p.getByRole('button',{name:'下一步',exact:true}).count(),0);for(let i=0;i<9;i++){await p.evaluate(()=>answerLesson(_lesson.question.answer));await p.getByRole('button',{name:'下一步',exact:true}).click();}assert.equal(await p.locator('#modal input,#modal textarea').count(),0);await p.getByRole('button',{name:'孩子说过了 · 家长确认',exact:true}).click();assert.equal(await p.evaluate(()=>state.english.lessons[0]),4);assert.equal(await p.evaluate(()=>Object.keys(state.english.review).length),0);assert.equal(await p.evaluate(()=>state.stars),3);await p.reload();assert.equal(await p.evaluate(()=>state.english.lessons[0]),4);});
test('story finishes with picture sequence and oral retelling, with no typing',async t=>{const p=await setup(t);await p.evaluate(()=>{switchTab('stories');showStory(1);});assert.equal(await p.evaluate(()=>state.stories.read.length),0);await p.evaluate(()=>{while(state.stories.currentPage<STORIES[0].p.length-1)nextStoryPage();showStoryQuiz(1);});assert.deepEqual(await p.evaluate(()=>state.stories.read),[1]);for(let i=0;i<4;i++){await p.evaluate(()=>answerReading(_reading.question.answer));await p.getByRole('button',{name:'下一步',exact:true}).click();}for(let i=0;i<3;i++){await p.evaluate(()=>{_reading.events.forEach((_,i)=>pickStoryEvent(i));});await p.getByRole('button',{name:'检查顺序',exact:true}).click();await p.getByRole('button',{name:'下一步',exact:true}).click();}assert.equal(await p.locator('#modal textarea,#modal input').count(),0);for(let i=0;i<3;i++)await p.getByRole('button',{name:'孩子讲过了 · 家长确认',exact:true}).click();assert.equal(await p.evaluate(()=>state.stories.training[1]),1);await p.reload();assert.equal(await p.evaluate(()=>state.stories.training[1]),1);});
test('old backups gain defaults and invalid new settings are rejected',async t=>{const p=await setup(t);const defaults=await p.evaluate(()=>normalizeState({stars:12,english:{learned:{cat:true}}}));assert.equal(defaults.numbers.difficulty,0);assert.deepEqual(defaults.english.lessons,{});assert.deepEqual(defaults.stories.training,{});assert.equal(await p.evaluate(()=>{try{normalizeState({numbers:{difficulty:99}});return false;}catch{return true;}}),true);});
test('all six english lessons complete and replay does not duplicate rewards',async t=>{const p=await setup(t);const result=await p.evaluate(()=>{for(let run=0;run<2;run++)ENGLISH_LESSONS.forEach((l,id)=>{startEnglishLessonForTheme(l.theme);if(_lesson.id!==id)throw Error('Wrong theme route');advanceLesson();for(let i=0;i<9;i++){answerLesson(_lesson.question.answer);advanceLesson();}finishLesson();finishLesson();});return {lessons:Object.values(state.english.lessons),stars:state.stars,missing:ENGLISH_LESSONS.flatMap(l=>l.words).filter(w=>!EN_WORD_AUDIO[w.w]).map(w=>w.w)};});assert.deepEqual(result.lessons,[4,4,4,4,4,4]);assert.equal(result.stars,18);assert.deepEqual(result.missing,[]);});
test('english resume and targeted review work after reload',async t=>{const p=await setup(t);await p.evaluate(()=>{startEnglishLesson(2);advanceLesson();answerLesson((_lesson.question.answer+1)%3);closeModal();});await p.reload();await p.evaluate(()=>startEnglishReview());assert.equal(await p.evaluate(()=>_lesson.id),2);await p.evaluate(()=>answerLesson(_lesson.question.answer));await p.getByRole('button',{name:'完成复习',exact:true}).click();assert.deepEqual(await p.evaluate(()=>state.english.review),{});await p.evaluate(()=>startEnglishLesson(2));assert.equal(await p.evaluate(()=>_lesson.step),1);assert.equal(await p.evaluate(()=>state.stars),0);});
test('all story guides have distinct choices and finish both ordering levels',async t=>{const p=await setup(t);const result=await p.evaluate(()=>{const failures=[];for(let level=0;level<2;level++){state.stories.readingLevel=level;for(const s of STORIES){showStory(s.id);state.stories.currentPage=s.p.length-1;showStoryQuiz(s.id);if(new Set(_reading.question.options.map(o=>o.cn)).size!==3)failures.push(s.id);for(let i=0;i<4;i++){answerReading(_reading.question.answer);advanceReading();}for(let i=0;i<3;i++){_reading.events.forEach((_,i)=>pickStoryEvent(i));checkStoryOrder();advanceReading();}for(let i=0;i<3;i++)finishReading();finishReading();}}return {failures,read:state.stories.read.length,training:Object.values(state.stories.training),stars:state.stars};});assert.deepEqual(result.failures,[]);assert.equal(result.read,50);assert.ok(result.training.every(n=>n===2));assert.equal(result.stars,250);});
test('wrong ordering is retryable and partial story progress survives reload',async t=>{const p=await setup(t);await p.evaluate(()=>{showStoryQuiz(4);for(let i=0;i<4;i++){answerReading(_reading.question.answer);advanceReading();}pickStoryEvent(1);pickStoryEvent(0);checkStoryOrder();});assert.deepEqual(await p.evaluate(()=>_reading.sequence),[]);assert.equal(await p.getByRole('button',{name:'下一步',exact:true}).count(),0);await p.reload();await p.evaluate(()=>showStoryQuiz(4));assert.equal(await p.evaluate(()=>_reading.step),1);});
test('malformed review references are rejected before restoring a backup',async t=>{const p=await setup(t);const result=await p.evaluate(()=>['length:1','constructor:1','-1:1','6:1','01:1','0:9'].map(key=>{if(validReviewKey(key))return false;try{normalizeState({english:{review:{[key]:1}}});return false;}catch{return true;}}));assert.ok(result.every(Boolean));});
test('parents can read the English prompt while recorded speech works without synthesis',async t=>{const p=await setup(t);await p.evaluate(()=>{startEnglishLesson(0);advanceLesson();for(let i=0;i<7;i++){answerLesson(_lesson.question.answer);advanceLesson();}synth=null;lessonAudio();});await p.getByText('家长提示 · 看文字',{exact:true}).click();assert.ok(await p.getByText(await p.evaluate(()=>_lesson.data.phrases[1]),{exact:true}).isVisible());await p.waitForFunction(()=>_audioEl&&!_audioEl.paused&&_audioEl.currentTime>.02);});
test('logic patterns isolate one visual feature and use AB, AAB or ABC rules',async t=>{const p=await setup(t);const failures=await p.evaluate(()=>{const fail=[];for(let level=0;level<3;level++)for(const dimension of ['color','shape','size'])for(let i=0;i<10;i++){state.logic.level=level;startLogicPattern(dimension);const q=_logicPattern;if(q.dimension!==dimension||q.sequence.length<q.cycle.length*2||q.options.length!==3||q.answer!==q.cycle[q.sequence.length%q.cycle.length]||q.cycle.length>3)fail.push({level,dimension});}return fail;});assert.deepEqual(failures,[]);});
test('wrong pattern does not reveal the answer and supports hints and retry',async t=>{const p=await setup(t);await p.evaluate(()=>{startLogicPattern('shape');answerLogicPattern(_logicPattern.options.find(s=>s!==_logicPattern.answer));});assert.equal(await p.locator('#logicPattern .correct').count(),0);assert.equal(await p.evaluate(()=>state.logic.completed.length),0);await p.getByRole('button',{name:'💡 看看重复的一组',exact:true}).click();assert.ok(await p.locator('#logicPattern .pattern-track').evaluate(el=>el.classList.contains('show-groups')));await p.evaluate(()=>{answerLogicPattern(_logicPattern.answer);answerLogicPattern(_logicPattern.answer);});assert.equal(await p.evaluate(()=>state.logic.completed.length),1);});
test('sorting uses four measurable dimensions with distinct visuals and repeat-safe scoring',async t=>{const p=await setup(t);const results=await p.evaluate(()=>{const out=[];for(const dim of ['size','length','height','quantity']){state.logic.level=1;startLogicSort(dim);const cards=[...document.querySelectorAll('[data-sort-value]')];cards.sort((a,b)=>+b.dataset.sortValue-+a.dataset.sortValue).forEach(b=>b.click());checkLogicSort();out.push(_logicSort.solved===false);resetLogicSort();cards.sort((a,b)=>+a.dataset.sortValue-+b.dataset.sortValue).forEach(b=>b.click());checkLogicSort();checkLogicSort();out.push(_logicSort.solved===true);}return {out,count:state.logic.completed.length};});assert.ok(results.out.every(Boolean));assert.equal(results.count,4);});
test('pattern hints circle full repeats while leaving the unfinished tail unmarked',async t=>{const p=await setup(t);const result=await p.evaluate(()=>{const old=Math.random;Math.random=()=>.99;state.logic.level=1;startLogicPattern('color');Math.random=old;hintLogicPattern();return [...document.querySelectorAll('.pattern-group')].map(el=>({size:el.querySelectorAll('.logic-token').length,border:getComputedStyle(el).borderTopColor}));});assert.deepEqual(result.map(g=>g.size),[3,3,2]);assert.equal(result[0].border,result[1].border);assert.equal(result[2].border,'rgba(0, 0, 0, 0)');});
test('mobile and desktop activity screens fit and capture previews',async t=>{const p=await setup(t);const dir=path.join(require('node:os').tmpdir(),'baby-learning-preview');require('node:fs').mkdirSync(dir,{recursive:true});for(const width of [390,1280]){await p.setViewportSize({width,height:900});for(const tab of ['numbers','english','stories','logic']){await p.evaluate(tab=>switchTab(tab),tab);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),tab+' page overflow');await p.screenshot({path:path.join(dir,tab+'-'+width+'.png'),fullPage:true});}for(const start of ['startLogicPattern("size")','startLogicSort("length")','startChallenge("make")','startEnglishLesson(0);advanceLesson()','state.stories.readingSteps={};showStoryQuiz(1);answerReading(_reading.question.answer);advanceReading()']){await p.evaluate(start=>eval(start),start);assert.ok(await p.locator('#modal').evaluate(el=>el.scrollWidth<=el.clientWidth),'modal overflow: '+start);await p.screenshot({path:path.join(dir,"activity-"+width+"-"+start.split("(")[0]+".png")});await p.evaluate(()=>closeModal());}}console.log('Previews: '+dir);});
